### ISSUE TITLE
Duration type incorrectly serialises as Time

### ISSUE THREAD

**Issue by dten** [HaXml/HaXml#1]
XML Durations are required to start with `-P` or `P` to indicate they are a period.

https://www.w3schools.com/xml/schema_dtypes_date.asp

the serialising for Duration misses the `P`
https://github.com/HaXml/HaXml/blob/main/src/Text/XML/HaXml/Schema/PrimitiveTypes.hs#L159

(it also writes a lot of 0's.. which is kind of annoying)

**Comment by juhp** [comment]
Thanks for the report - can you test this change I pushed to the patch-1duration branch?

**Comment by dten** [comment]
hey thanks for working on this. I think that change would mean that a zero duration results in simply `P` which is not valid, as i read the schema it has to specify some numbers, so zero would be `P0S`

https://www.w3.org/TR/xmlschema11-2/#duration

**Comment by juhp** [comment]
Thanks for reviewing.  Seems there is no canonical form for a zero duration?
I suppose `P0S` is good enough though it doesn't feel perfect to me. :-)

Okay I have reworked the change to hopefully be a bit better.

**Comment by dten** [comment]
looking better. i do have a couple of local tests that assert what `simpleTypeText` text returns

so the remaining question is should you be able to produce `-P0S`, i have this test (it used to have more zeros) which fails and i'm not sure what the outcome should be. i'm not sure it really matters though

`simpleTypeText (Duration False 0 0 0 0 0 0) `shouldBe` "-P0S"`

**Comment by juhp** [comment]
Okay I did ponder whether to render `-P0S`, I don't mind adding it.

**Comment by juhp** [comment]
How about now? 🤞

**Comment by dten** [comment]
👋 me again. it turns out I made an error and the rest of the world doesn't like it.

according to dotnet `P0S` is not a valid duration, it should be `PT0S`

```
using System;
using System.Xml;

public class Program
{
  public static void Main()
  {
    Console.WriteLine(XmlConvert.ToTimeSpan("PT0S"));
    Console.WriteLine(XmlConvert.ToTimeSpan("P0S"));
  }
}
```
